### ISSUE TITLE
Unsubscription unreliability (possible leak)

### ISSUE THREAD

**Issue by bolein** [skiff2011/baseadapter#1]
https://github.com/skiff2011/baseadapter/blob/cbe1c9ac1b169c0e6e3b8594c2146fda66b71811/library/src/main/java/eu/theappshop/baseadapter/adapter/ViewPagerAdapter.java#L91

**Comment by skiff2011** [comment]
Я об этом долго думал, с ресайклером все ок в этом плане, там есть методы register/unregister которые дергает сама вьюха в адаптере, а втюпейжер использует такой метод 
`void setViewPagerObserver(DataSetObserver observer) {
        synchronized (this) {
            mViewPagerObserver = observer;
        }
    }`
и переопределить его нельзя, теоретически метода saveState покрывает следуюший кейсы:

- смена ориентации

- смена фрагментов(replace -> popbackStack)

так как вьюха пересоздается.
А когда активити уничтожается этот метод так же в теории будет дергатся если у вьюпейжера есть ид, так как будет срабатывать автоматическое сохранение состояния.
Но я думаю что есть кейсы которые я не рассмотрел

**Comment by skiff2011** [comment]
возможно использовать WeakReference?

**Comment by skiff2011** [comment]
потестил ресайклер с ним также проблемы

**Comment by bolein** [comment]
fixed by #4

**Comment by skiff2011** [comment]
fixed for recyclerview by #5
