### ISSUE TITLE
No titles - doesn't work with TabLayout for now

### ISSUE THREAD

**Issue by bolein** [skiff2011/baseadapter#2]
https://github.com/skiff2011/baseadapter/blob/cbe1c9ac1b169c0e6e3b8594c2146fda66b71811/library/src/main/java/eu/theappshop/baseadapter/adapter/ViewPagerAdapter.java#L140

**Comment by skiff2011** [comment]
Added new VM type that can provide tittle for using viewpager with this tablayout

**Comment by bolein** [comment]
@skiff2011 pls use issue reference in commit next time  like this #2
